"""Price name and type changed

Revision ID: 0d99bc457f75
Revises: 6466655c9159
Create Date: 2025-06-14 07:07:21.523895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d99bc457f75'
down_revision = '6466655c9159'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant-pizzas', schema=None) as batch_op:
        # batch_op.add_column(sa.Column('_price', sa.Integer(), nullable=False,))
        # batch_op.drop_column('price')
        batch_op.alter_column(column_name='price',type_=sa.Integer(),new_column_name='_price')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant-pizzas', schema=None) as batch_op:
        # batch_op.add_column(sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        # batch_op.drop_column('_price')
        batch_op.alter_column(column_name='_price',type_=sa.DOUBLE_PRECISION(),new_column_name='price')

    # ### end Alembic commands ###
